### ISSUE TITLE
Emojis are not encoded and will create an invalid xml

### ISSUE THREAD

**Issue by alexander-schranz** [jackalope/jackalope#339]
It seems when an emoji (🍔 ) is added to the xml it tries to insert the emoji without encode it and then mysql seems cut the xml and nothing after the emoji exist. You can only fix it by manually closing the tags `</sv:value></sv:property></sv:node>` in the database but all properties after the emoji are lost. The emoji should correctly be encoded instead of being inserted as own character.

Running: PHP 7.0
MySql: 5.6
Encoding: UTF8 (not mb4!)

**Comment by dbu** [comment]
this probably belongs into https://github.com/jackalope/jackalope-doctrine-dbal 

this is even for values, not only for node/property names, right? i am not exactly sure where the escaping should/can happen. i think the actual xml serialization happens [here](https://github.com/jackalope/jackalope-doctrine-dbal/blob/67c8f17225dd727b052dbb5a0db7e52061a1896e/src/Jackalope/Transport/DoctrineDBAL/Client.php#L857) - if you see something that could be fixed there, i am happy for any pull requests. ideally you could first add tests to phpcr-api-tests to demonstrate the problem and so that we can see on what systems it happens.

**Comment by alexander-schranz** [comment]
@dbu thank you for your fast response.
Can you show me also where the property value is set to the xml or where the xml is built?

**Comment by dbu** [comment]
that would be the
[propsToXml](https://github.com/jackalope/jackalope-doctrine-dbal/blob/67c8f17225dd727b052dbb5a0db7e52061a1896e/src/Jackalope/Transport/DoctrineDBAL/Client.php#L1175)
method

**Comment by alexander-schranz** [comment]
by supporting utf8mb4 (https://github.com/jackalope/jackalope-doctrine-dbal/pull/354) this is not longer an issue which crash the database. so I will close this issue.
