### ISSUE TITLE
Allow to indicate preferred Session class for Repository::login()

### ISSUE THREAD

**Issue by holtkamp** [jackalope/jackalope#350]
Currently, [Repository::login](https://github.com/jackalope/jackalope/blob/f9509dadc2cfa781b7dc29d6f374c40390be4dc2/src/Jackalope/Repository.php#L155) always returns an object of class `Session`. It would be nice to be able to specify any kind of class name that implements the `SessionInterface`. 

This makes it easier to use different kind of Sessions and configure them properly in a Dependency Injection Container that uses type-hinting. Next to a normal Session, a "ReadReplicaSession" might be involved, which is typehinted using a ReadReplicaSessionInterface.

```php
interface ReadReplicaSessionInterface extends \PHPCR\SessionInterface{
    //dummy file to allow DependencyInjectionContainer type-hinting
}

class ReadReplicaSession extends \Jackalope\Session implements ReadReplicaSessionInterface{
    // dummy file to allow DependencyInjectionContainer type-hinting
}

class PerformSomeWritesOnContentRepository
{
    /**
     * @var \PHPCR\SessionInterface
     */
    private $session;
    public function __construct(\PHPCR\SessionInterface $normalSession)
    {
        $this->session = $normalSession
    }
}

class OnlyPerformReadsOnContentRepository
{
    /**
     * @var ReadReplicaSessionInterface
     */
    private $session;
    public function __construct(ReadReplicaSessionInterface $readReplicaSession)
    {
        $this->session = $readReplicaSession
    }
}

**Comment by dbu** [comment]
first off: the jackalope codebase is rather old and it sometimes shows :-/

the "factory" that is used in the repository is a bit like a service locator / container. you can define your own factory and inject that on repository creation. the factory can translate the jackalope class names into any class it wants (thats part of why we use the factory rather than just having `new` all over the place). you then need more than one repository instance for the "same" phpcr, but you need that anyways because the login does not provide further options as to what is wanted. would that cover your use case?

i think your specific use case might also be covered by user permissions. if one login is with a user that is not allowed to write, it would also be a read only session. afaik the whole of jackalope codebase does not check on this however, so you would only get storage errors on `save()`. thats however not just a thing of the session, there are also write operations on `Node` and `Property`. the different database / jackrabbit user would make you detect the problem, though not close to the source, so you'd have to debug where you accidentally change data.

**Comment by holtkamp** [comment]
Thanks for the detailed response! Yeah I think I understand the idea of the factory which is being injected into the Repository. I could create a custom Factory, that returns a custom Repository, which uses a specific Session class, but I think the following approach is easier:

```php
class Repository implements RepositoryInterface
{
    /**
     * Allow to indicate what kind of Session class is used
     * @var string
     */
    public $sessionClass = Session::class;

    public function login(CredentialsInterface $credentials = null, $workspaceName = null)
    {
        ...

        /** @var $session Session */
        $session = $this->factory->get($this->sessionClass, [$this, $workspaceName, $credentials, $this->transport]);
       
        ...

        return $session;
    }
}
```


Now a DependencyInjectionContainer configuration could look something like:

```php
\Jackalope\Session::class => function (\Doctrine\DBAL\Driver\Connection $connection): \Jackalope\Session {
        $factory = new \Jackalope\RepositoryFactoryDoctrineDBAL();
        $repository = $factory->getRepository([
            'jackalope.doctrine_dbal_connection' => $connection,
        ]);

        return $repository->login(new \PHPCR\SimpleCredentials(null, null));
    },
\Jackalope\Session\ReadReplica::class => function (\Doctrine\DBAL\Driver\Connection $connection): \Jackalope\Session\ReadReplica {
        $factory = new \Jackalope\RepositoryFactoryDoctrineDBAL();
        $repository = $factory->getRepository([
            'jackalope.doctrine_dbal_connection' => $connection,
        ]);
        $repository->sessionClass = \Jackalope\Session\ReadReplica::class;

        return $repository->login(new \PHPCR\SimpleCredentials(null, null));
    },
```

Or am I thinking too simplistic?

**Comment by dbu** [comment]
the problem i have with this approach is that we exposes internals, it feels to me like we try to be more generic than necessary. i don't see at the moment where the additional generic flexibility of setting any class as session class would be useful. it would also make it impossible for the factory to use a different session class because it can't know what class is being used.

instead, jackalope itself could have the ReadReplica (or ReadonlySession or whatever) class and just provide an option in the repository that makes it create readonly clients.

i think we should either do nothing and you can use the factory approach, which is a few lines of code extending the provided factory with a special case for creating the session. or we can do a PR to add readonly support to the session (and probably node as well) that can be activated with a repository option. if you want to work on a pull request for that, please go ahead - i can imagine merging that.

either way, the only plus over having read-only only on the storage credentials is better error reporting. if you configure the dbal client with credentials that are not allowed to write, you also have a read-only client, but only get an error on `save()` if there where changes made to any nodes. is that worth the effort?

**Comment by dbu** [comment]
uh oh, i just notice that there are two kind of factories involved. i think we have not been talking about the same thing. there is indeed the repository factory which is part of the PHPCR api. what i was thinking about, however, is the [Jackalope\Factory](https://github.com/jackalope/jackalope/blob/master/src/Jackalope/Factory.php) class

with that, it could look like this:

```
class ReadReplicaFactory extends Jackalope\Factory
{
    public function get($name, array $params = [])
    {
        if (ReadReplicaSession::class === $name) {
            return new ReadReplicaSession();
        }

        parent::get($name, $params);
    }
}
```

and with that factory, you can create a second instance of the RepositoryFactoryDoctrineDBAL class with the factory in the option (jackalope.factory)[https://github.com/jackalope/jackalope-doctrine-dbal/blob/d810fd88237d7537c431c38005150db1c1f9d8a3/src/Jackalope/RepositoryFactoryDoctrineDBAL.php#L46]

**Comment by holtkamp** [comment]
Aah, of course, that way requires less customization. You probably mean:

```php
use Jackalope\Factory;
use Jackalope\Session;
class ReadReplicaFactory extends Factory
{
    public function get($name, array $params = [])
    {
        if (Session::class === $name) {
            $name = ReadReplicaSession::class; //Simply intercept the requested name
        }

        return parent::get($name, $params);
    }
}
```

Thanks for the pointer, let me see how this works out.

**Comment by dbu** [comment]
indeed, your solution for the factory is better as it avoids duplicating things from the base factory. although there is some magic in injecting the factory to classes only if they are in Jackalope namespace, if i remember correctly - that might not work as expected with your code.

lets see if that works out. note that the Node created by such a session would still allow setProperty and the Property would allow setValue, which are basically the write operations of PHPCR...

**Comment by holtkamp** [comment]
>although there is some magic in injecting the factory to classes only if they are in Jackalope namespace, if i remember correctly

Indeed, I saw it, but not a problem, since the `ReadReplicaSession` class is a dummy class and extends `Jackalope\Session`. 

>note that the Node created by such a session would still allow setProperty and the Property would allow setValue, which are basically the write operations of PHPCR.

Ok, thanks. The UseCase that will have the ReadReplicaSession dependency injected is aware that it should be used for "read" operations only 👍 

**Context: synchronize a PHP ContentRepository to local filesystem**
@dbu because I saw in [your profile](http://davidbu.ch/mann/) you worked quite a bit with caching, the use case might interest you. I use the PHP ContentRepository running on a MySQL Database in combination with [FlySystem's MountManager](https://flysystem.thephpleague.com/docs/advanced/mount-manager/) to quickly populate a server container's (Heroku dyno) local disk. As soon as the container starts, its file system is mostly empty. A synchronisation mechanism copies the content (typically HTML content) in a PHP ContentRepository to .html files on the container's filesystem, which can then be served by Apache directly, omitting the application server. So actually it is "warming" the file-level cache layer 🤓 

Because this synchronisation run is quite a "hit" on the database (eventual content is around 100k entries), we use a ReadReplica for it instead of the master to prevent performance problems on server start.

**Comment by dbu** [comment]
that sounds super interesting. please tell me if you ever do a blog post or similar write up on the solution and the reasons to go with PHPCR for this.

**Comment by holtkamp** [comment]
sure! Hopefully "some day" I will have some time for write-ups. 

The mechanism is actually quite simple. A small trick we needed to manipulate cache expiration time is using a `.htaccess` rule with expiration times _relative_ to the modification time:

```
<FilesMatch "\.(html)$">
       ExpiresActive on
       ExpiresDefault "modification plus 14 days"
    </FilesMatch>
```

By manipulating the modification time when the .html file is written to disk, you can achieve quite good control. Combining this file-based caching at the origin-server with caching at an [edge-server](https://www.cloudflare.com/learning/cdn/glossary/edge-server/), a big amount of (static) content can be served from cache.
