### ISSUE TITLE
Export/import error with skipBinary option set to true

### ISSUE THREAD

**Issue by EmmanuelVella** [jackalope/jackalope#368]
Hello !

I created an export using the `$skipBinaries => true` option, and when I try to restore I have the following error : 

`HTTP 409: /cms/media/[...any file...]/jcr:content: mandatory property {http://www.jcp.org/jcr/1.0}data does not exist`.

Indeed in the export, each file `content` node seems to miss the `data` property, and jackrabbit complain about it. I think the magic happens here : https://github.com/jackalope/jackalope/blob/master/src/Jackalope/ImportExport/ImportExport.php#L358 

I'm using jackalope/jackalope on current version (`1.4.2`) and jackrabbit latest stable (`2.20.4`).

Do I miss something ? Thank you !

**Comment by dbu** [comment]
hi emanuele, when skipping binaries, the idea is that the binaries are not exported, so it seems correct that the data property is missing as that was the binary.

for a backup, you'd need to not skip binaries.

if you want to load the dump as is without binaries, i think you need to manipulate the xml and either add an empty dummy data property or remove the whole jcr:content node because data is mandatory.

afaik the skip binaries flag is on a lower level and does not know/care about the node types and required binary properties.

**Comment by EmmanuelVella** [comment]
Hi David ! Thank you for your feedback.

Actually it's not for a backup, but to get a production version of the database to be able to preview some pages design (thus I don't need files which increase a lot the dump size).

I will try your solution and keep you informed in this thread if it worked !
